#!/bin/sh 

# Note that the short arguments are used for OSx and Ubuntu comptability

if tty -s ; then
  ONTTY=-s
  set -x
else
  ONTTY=
fi

if [ -s /tmp/worker.pid ] ; then
    if kill -0 `cat /tmp/worker.pid` ; then
        logger $ONTTY -i -t WORKER -p user.notice Process `cat /tmp/worker.pid` still running. Exiting.
        exit 0
    else
        logger $ONTTY -i -t WORKER -p user.notice Process `cat /tmp/worker.pid` died.  Starting anew.
    fi
fi

echo $$ > /tmp/worker.pid

cd ~/worker

logger $ONTTY -i -t WORKER -p user.info Worker starting. 

while [ -s /tmp/worker.pid ] ; do
    ./ProcessQueue.py
    status=$?
    if [ $status -ne 0 ] ; then
	logger $ONTTY -i -t WORKER -p user.warning ProcessQueue returned an error ${status}.  Taking a nap.
        sleep 60
    fi
    LOCAL=$(git rev-parse master)
    REMOTE=$(git rev-parse origin/master)
    if [ $LOCAL != $REMOTE ] ; then
        git pull
        # Now restart
        logger $ONTTY -i -t WORKER -p user.notice Restarting after update from $LOCAL to $REMOTE
	rm /tmp/worker.pid
	exec $0
    fi
done
logger $ONTTY -i -t WORKER -p user.notice Stopping 
exit 0
